nft-delete-rule.py: add file
New example file.

By the time of this commit, the example fails with:

=== 8< ===
ERROR: running JSON cmd: Error: Expected object, got string
{"nftables": [{"metainfo": {"json_schema_version": 1}}, {"delete": {"fa[..]
^
internal:0:0-0: Error: Parsing command array at index 1 failed.
=== 8< ===

I suspect because an internal bug in nftables.

Signed-off-by: Arturo Borrero Gonzalez <arturo@netfilter.org>